// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo2IB-IFyvCBgB7MBJlVyUYmqr5yL36q8',
    appId: '1:126194822946:web:b7c40c16018ade12a37f7b',
    messagingSenderId: '126194822946',
    projectId: 'currencyapp-e6a2b',
    authDomain: 'currencyapp-e6a2b.firebaseapp.com',
    storageBucket: 'currencyapp-e6a2b.firebasestorage.app',
    measurementId: '"G-JPKMD83QX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo2IB-IFyvCBgB7MBJlVyUYmqr5yL36q8',
    appId: '1:126194822946:web:b7c40c16018ade12a37f7b',
    messagingSenderId: '126194822946',
    projectId: 'currencyapp-e6a2b',
    storageBucket: 'currencyapp-e6a2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACQ7JV0aZ5_P0EvmRGz7_H564vqwuiDfo',
    appId: '1:142536809662:ios:9c356009938d7ab84752ef',
    messagingSenderId: '126194822946',
    projectId: 'mobile-a0f4f',
    storageBucket: 'mobile-a0f4f.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACQ7JV0aZ5_P0EvmRGz7_H564vqwuiDfo',
    appId: '1:142536809662:ios:9c356009938d7ab84752ef',
    messagingSenderId: '142536809662',
    projectId: 'mobile-a0f4f',
    storageBucket: 'mobile-a0f4f.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTM9qC6fNDYYTU8wkweSWn5cbhztUiC1M',
    appId: '1:142536809662:web:76490f479950fe9f4752ef',
    messagingSenderId: '142536809662',
    projectId: 'mobile-a0f4f',
    authDomain: 'mobile-a0f4f.firebaseapp.com',
    storageBucket: 'mobile-a0f4f.firebasestorage.app',
    measurementId: 'G-H3FDHXLDY1',
  );
}
